#!/bin/bash
  
  # Just editing this file won't affect the permissions. After editing it, you
  # also need to execute it.
  #
  # The creator of this repository is YOUR_SCIPER_HERE.
  
  thisrepo="projects/rosa-private"
  
  tail -2 "$0" | ssh git@laragit.epfl.ch setperms ${thisrepo}
  
  exit $_
  
  # **Do not** add new lines after the following two!
  WRITERS kuncak edarulov ekneuss
  READERS @lara
