#!/bin/bash

sbt package
sbt script

echo "straightline"
./leon --functions=doppler:dopplerRefactored:rigidBody2:rigidBody2Refactored:jetEngine:jetEngineRefactored:turbine1:turbine1Refactored:turbine2:turbine2Refactored:turbine3:turbine3Refactored:sine:sqroot:sineOrder3 testcases/real/techreport/Straightline.scala 
./leon --solverIterations=10:30 --solverPrecision=1.0e-5:1.0e-10 --functions=doppler:dopplerRefactored:rigidBody2:rigidBody2Refactored:jetEngine:jetEngineRefactored:turbine1:turbine1Refactored:turbine2:turbine2Refactored:turbine3:turbine3Refactored:sine:sqroot:sineOrder3 testcases/real/techreport/Straightline.scala 

echo "straightline with errors"
./leon --solverIterations=10:30 --solverPrecision=1.0e-5:1.0e-10 --functions=dopplerRefactoredWithError:jetEngineRefactoredWithError:turbine1RefactoredWithError:turbine2RefactoredWithError:turbine3RefactoredWithError testcases/real/techreport/StraightlineWithError.scala

echo "loops"
./leon --solverIterations=10:30 --solverPrecision=1.0e-5:1.0e-10 --functions=nextItem:mean1000:mean4000:sine:pendulum50:pendulum1000 testcases/real/techreport/RunningAvrg.scala testcases/real/techreport/Pendulum.scala 

echo "discontinuities"
./leon --solverIterations=10:30 --solverPrecision=1.0e-5:1.0e-15 --functions=squareRoot:squareRoot3Invalid:linearFit:quadraticFit:quadraticFitErr:quadraticFit2:quadraticFit2Err:styblinski:styblinskiErr:sortOfStyblinski:sortOfStyblinskiErr:jetApprox:jetApproxErr:jetApproxGoodFit:jetApproxGoodFitErr:jetApproxBadFit:jetApproxBadFitErr  testcases/real/techreport/Discontinuity.scala
